# Generated by Django 4.0.5 on 2023-04-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
