# Generated by Django 4.0.5 on 2023-04-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
