# Generated by Django 4.0.5 on 2023-04-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rating_score_alter_user_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Vilnius', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='hour_rate',
            field=models.CharField(default='10-30', max_length=10),
        ),
    ]
